version: '3'
services:
  vkbs_bot:
    restart: always
    build:
      context: git@github.com:BMSTU-Schedule/vk-bmstu-schedule-bot.git
    env_file: vkbot_conf.env
    volumes: 
      - "/var/bs_vault:/var/bs_vault"
    depends_on:
      - database

  tgbs_bot:
    restart: always
    build:
      context: git@github.com:BMSTU-Schedule/telegram-bmstu-schedule-bot.git
    env_file: tgbot_conf.env
    volumes:
      - "/var/bs_vault:/var/bs_vault"
    entrypoint: python3 -u main.py
  
  bs_web:
    restart: always
    build:
      context: git@github.com:BMSTU-Schedule/bmstu-schedule-web.git
    volumes:
      - "/var/bs_vault:/ics"
    ports:
      - "8000:8000"

  database:
    restart: always
    image: postgres:11
    env_file: database_conf.env
    volumes:
      - ~/var/bs_vault/postgres:/var/lib/postgresql/data
