version: '3.7'
services:
  vkbs_bot_test:
    restart: always
    build:
      context: ./vk-bmstu-schedule-bot/
    env_file: vkbot_conf.yml
    volumes: 
      - "/var/bs_vault:/var/bs_vault"
    entrypoint: ./vk-bmstu-schedule-bot

  tgbs_bot_test:
    restart: always
    build:
      context: ./telegram-bmstu-schedule-bot/
    env_file: tgbot_conf.yml
    volumes:
      - "/var/bs_vault:/var/bs_vault"
    entrypoint: python3 -u main.py
  
  bs_web_test:
    restart: always
    build:
      context: ./bmstu-schedule-web
    volumes:
      - "/var/bs_vault:/ics"
    ports:
      - "8000:8000"
